# Generated by Django 3.2 on 2023-04-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
